// <auto-generated />
using System;
using Employee_management_system.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_management_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee_management_system.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Sales"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "IT"
                        });
                });

            modelBuilder.Entity("Employee_management_system.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "123 Colombo Srilanka",
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2024, 2, 26, 12, 29, 32, 828, DateTimeKind.Local).AddTicks(3575),
                            Department = "Sales",
                            Email = "alice@gmail.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            MobileNumber = "0711234567"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "456 Colombo Srilanka",
                            Birthday = new DateTime(1991, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2024, 2, 26, 12, 29, 32, 828, DateTimeKind.Local).AddTicks(3596),
                            Department = "Marketing",
                            Email = "kamal@gmail.com",
                            FirstName = "Kamal",
                            LastName = "Jones",
                            MobileNumber = "0771234567"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "789 Colombo Srilanka",
                            Birthday = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2024, 2, 26, 12, 29, 32, 828, DateTimeKind.Local).AddTicks(3602),
                            Department = "IT",
                            Email = "amal@gmail.com",
                            FirstName = "Amal",
                            LastName = "Perera",
                            MobileNumber = "0751237896"
                        });
                });

            modelBuilder.Entity("Employee_management_system.Models.EmployeeDepartment", b =>
                {
                    b.Property<int>("EmployeeNo")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentNo")
                        .HasColumnType("int");

                    b.HasKey("EmployeeNo", "DepartmentNo");

                    b.HasIndex("DepartmentNo");

                    b.ToTable("EmployeeDepartments", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeNo = 1,
                            DepartmentNo = 1
                        },
                        new
                        {
                            EmployeeNo = 2,
                            DepartmentNo = 2
                        },
                        new
                        {
                            EmployeeNo = 3,
                            DepartmentNo = 3
                        });
                });

            modelBuilder.Entity("Employee_management_system.Models.EmployeeDepartment", b =>
                {
                    b.HasOne("Employee_management_system.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_management_system.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
